# Site settings
title: Rahendz Blog
email: rahendz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: rahendz
email: rahendz@gmail.com
facebook_username: rahendz
twitter_username: rahendz
github_username: rahendz
address:
  - line: rahendzlab
  # Feel free to add more lines here
telephone: 62-896-7180-1516
copyright: 2017 rahendz

# API settings
google_api_key: AIzaSyAp5cKSXQwmZ67u7mqQdHxYTlX1Nj7ieP0

# Build settings
markdown: kramdown