---
title: Rahendz Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: rahendz@gmail.com
description: 'Prefer coffee and smoking rather than tea and a biscuit. I love my family
  and friends. Love hang-out with friends and foe, especially camping or backpacking
  anyplace, anywhere. Mostly for find some inspiration, killing times and cooling
  down the brain. Im'' tipically a Friendly, Outgoing and Responsive Personality.
  Enthusiastic, Consciensious and Hardworking also an Independent and Team Worker

'
baseurl: ''
url: ''
twitter_username: rahendz
github_username: rahendz
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
