# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rahendz Blog
email: rahendz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Prefer coffee and smoking rather than tea and a biscuit. I love my family and friends. Love hang-out with friends and foe, especially camping or backpacking anyplace, anywhere. Mostly for find some inspiration, killing times and cooling down the brain. Im' tipically a Friendly, Outgoing and Responsive Personality. Enthusiastic, Consciensious and Hardworking also an Independent and Team Worker
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rahendz
github_username:  rahendz

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
