---
title: Rahendz Blog
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: rahendz@gmail.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: ''
owner: rahendz
facebook_username: rahendz
twitter_username: rahendz
github_username: rahendz
address:
- line: rahendzlab
telephone: 62-896-7180-1516
copyright: 2017 rahendz
google_api_key: AIzaSyAp5cKSXQwmZ67u7mqQdHxYTlX1Nj7ieP0
markdown: kramdown
